# Site Info
title: 'Lunallena TIL Blog'
tagline: '루나의 TIL 기술 블로그'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ''
url: 'https://lunayyko.github.com'
logo: '/public/logo.png'

# Site configurations
gems:
  -jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss  
pagination: enabled:true
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact 
author: 
  name: YooYoung
  description: A passionate <strong>developer</strong>
gravatar: 7e5150e6f53a595f8619f20371ddd613 # md5 hash of your email address
contact:
  linkedin:  https://www.linkedin.com/in/lunayyko
  github:    https://github.com/lunayyko
  # facebook:  <hide>

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://codinfox.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/linus.jpeg
  caption: '리누스 토발즈님'

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'G-QYYQ1T6EXK' # leave blank if you don't want google analytics
disqus_short_name: ' ' # leave blank if you don't want disqus
plugins: [jekyll-paginate]

# Gem
gems:
  - jekyll-paginate
paginate: 10

# Rouge
highlighter: rouge